### PR TITLE
fix cursor placement

### LINKED ISSUE #4: Cursor is off by 1 in Atom 1.1.0
Greti-Syntax suffers from the same issue that was recently fixed in Seti-Syntax:

https://github.com/jesseweed/seti-syntax/issues/106
https://github.com/jesseweed/seti-syntax/pull/107

### PR DESCRIPTION
**Pull request by jfairley**
fixes #4 

same fix as https://github.com/jesseweed/seti-syntax/pull/107

### CODE REVIEW

**Comment by iCodeForBananas** [comment]
I can confirm this works.
@jfairley  @mikestephens

**Comment by michaelstephens** [comment]
Awesome! Sorry for the delay, life is hectic. Thanks for your work!

**Comment by michaelstephens** [comment]
Released in v0.6.0

**Comment by jfairley** [comment]
:+1:

**Pull request merged**
